-- Insert categories
INSERT INTO category (id, name, description) VALUES
(nextval('category_seq'), 'Electronics', 'Consumer electronics and gadgets'),
(nextval('category_seq'), 'Clothing', 'Apparel for men, women, and children'),
(nextval('category_seq'), 'Books', 'A wide range of reading materials'),
(nextval('category_seq'), 'Home Goods', 'Items for furnishing and decorating your home'),
(nextval('category_seq'), 'Sports & Outdoors', 'Equipment and gear for various activities'),
(nextval('category_seq'), 'Beauty & Personal Care', 'Cosmetics, skincare, and personal hygiene products'),
(nextval('category_seq'), 'Toys & Games', 'Items for entertainment and play'),
(nextval('category_seq'), 'Automotive', 'Parts and accessories for vehicles'),
(nextval('category_seq'), 'Food & Beverage', 'Groceries and drinks'),
(nextval('category_seq'), 'Jewelry', 'Fine and fashion jewelry'),
(nextval('category_seq'), 'Watches', 'Timepieces for various styles'),
(nextval('category_seq'), 'Bags & Luggage', 'Carrying solutions for travel and everyday use'),
(nextval('category_seq'), 'Shoes', 'Footwear for different occasions'),
(nextval('category_seq'), 'Furniture', 'Items to furnish living spaces'),
(nextval('category_seq'), 'Office Supplies', 'Materials for work and study'),
(nextval('category_seq'), 'Pet Supplies', 'Items for animal care'),
(nextval('category_seq'), 'Health & Wellness', 'Products for maintaining a healthy lifestyle'),
(nextval('category_seq'), 'Tools & Home Improvement', 'Equipment for DIY projects and repairs'),
(nextval('category_seq'), 'Musical Instruments', 'Instruments for creating music'),
(nextval('category_seq'), 'Art Supplies', 'Materials for artistic expression'),
(nextval('category_seq'), 'Craft Supplies', 'Materials for various crafts and hobbies'),
(nextval('category_seq'), 'Garden & Outdoor', 'Items for gardening and outdoor living'),
(nextval('category_seq'), 'Baby Products', 'Items for infants and toddlers'),
(nextval('category_seq'), 'Software', 'Computer programs and applications'),
(nextval('category_seq'), 'Video Games', 'Interactive entertainment'),
(nextval('category_seq'), 'Movies & TV Shows', 'Films and television series'),
(nextval('category_seq'), 'Music', 'Audio recordings'),
(nextval('category_seq'), 'Collectibles', 'Items of interest to collectors'),
(nextval('category_seq'), 'Travel Accessories', 'Items to enhance travel experiences'),
(nextval('category_seq'), 'Party Supplies', 'Items for celebrations and events'),
(nextval('category_seq'), 'Kitchen Appliances', 'Appliances for kitchen use'),
(nextval('category_seq'), 'Fitness Equipment', 'Equipment for exercise and fitness'),
(nextval('category_seq'), 'Home Decor', 'Decorative items for the home');


-- Insert products for each category
-- Electronics
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Smartphone X', 'High-performance smartphone with advanced features', 150, 999.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Wireless Headphones', 'Over-ear headphones with noise cancellation', 200, 149.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Smart TV 55 inch', '4K UHD Smart TV with HDR', 100, 699.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Laptop Pro 14', 'Thin and light laptop for professionals', 120, 1299.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Tablet 10 inch', 'Versatile tablet for work and entertainment', 180, 299.20),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Bluetooth Speaker', 'Portable wireless speaker with rich sound', 250, 79.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Smartwatch', 'Fitness tracker and smartwatch with notifications', 160, 199.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Digital Camera', 'Mirrorless camera with high-resolution sensor', 80, 749.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Gaming Console', 'Next-generation gaming console', 90, 499.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'USB External Hard Drive 1TB', 'Portable storage solution', 300, 59.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Wireless Mouse', 'Ergonomic wireless mouse for office use', 220, 25.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Keyboard', 'Mechanical keyboard with customizable RGB lighting', 140, 129.90),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Monitor 27 inch', 'Full HD monitor for work and gaming', 110, 249.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Power Bank', 'Portable charger for mobile devices', 280, 35.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Smart Home Hub', 'Central control for smart home devices', 130, 89.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'VR Headset', 'Virtual reality headset for immersive experiences', 70, 399.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Printer', 'All-in-one inkjet printer with Wi-Fi', 105, 179.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Soundbar', 'Home theater soundbar with subwoofer', 95, 279.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Streaming Device', 'Device for streaming movies and TV shows', 210, 49.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'E-reader', 'Digital book reader with long battery life', 170, 119.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Camera Drone', 'High-quality camera drone for aerial photography', 60, 899.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Portable Projector', 'Compact projector for home and travel', 85, 349.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'DJ Controller', 'Professional DJ controller for mixing music', 40, 449.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Satellite Radio', 'Portable satellite radio receiver', 120, 99.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Voice Recorder', 'Digital voice recorder for lectures and meetings', 190, 69.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Retro Turntable', 'Vintage-style turntable for vinyl records', 75, 179.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Home Security Camera', 'Wireless home security camera system', 115, 249.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Car Audio System', 'In-car audio system with subwoofer', 55, 399.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Marine Radio', 'Waterproof marine radio for boats', 90, 149.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Electronics'), 'Ham Radio Transceiver', 'Two-way radio transceiver for amateur radio', 30, 299.00);

-- Clothing
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s T-Shirt (Cotton)', 'Comfortable cotton t-shirt for everyday wear', 500, 19.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Jeans (Slim Fit)', 'Slim fit denim jeans for women', 450, 39.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Kids'' Hoodie (Fleece)', 'Warm fleece hoodie for children', 600, 24.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Dress Shirt (Formal)', 'Formal long-sleeved dress shirt for men', 300, 49.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Summer Dress (Floral)', 'Light and airy floral print summer dress', 350, 35.20),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Casual Shorts (Chino)', 'Comfortable chino shorts for casual outings', 400, 29.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Blouse (Silk)', 'Elegant silk blouse for special occasions', 250, 59.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Kids'' Leggings (Stretch)', 'Stretchy and comfortable leggings for kids', 550, 14.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Sweater (Wool)', 'Warm wool sweater for cold weather', 280, 69.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Skirt (A-Line)', 'Classic A-line skirt for various styles', 320, 32.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Polo Shirt (Pique)', 'Classic pique knit polo shirt', 480, 27.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Jacket (Denim)', 'Stylish denim jacket for all seasons', 310, 45.90),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Kids'' Pajamas (Cotton)', 'Soft cotton pajamas for a comfortable sleep', 620, 18.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Suit (Two-Piece)', 'Formal two-piece suit for business or events', 150, 199.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Trousers (Wide Leg)', 'Trendy wide-leg trousers for a fashionable look', 290, 42.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Underwear (Boxer Briefs - 3 Pack)', 'Comfortable boxer briefs in a pack of three', 700, 22.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Socks (Cotton - 5 Pack)', 'Soft cotton socks in a pack of five', 800, 12.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Kids'' Dress (Party)', 'Elegant party dress for girls', 200, 38.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Coat (Winter)', 'Warm and durable winter coat', 180, 129.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Scarf (Silk)', 'Luxurious silk scarf with a beautiful pattern', 330, 31.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Swim Trunks', 'Quick-drying swim trunks for beach or pool', 420, 28.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Yoga Pants', 'High-waisted yoga pants for comfort and flexibility', 580, 34.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Kids'' Raincoat', 'Waterproof raincoat with hood', 490, 26.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Leather Belt', 'Genuine leather belt for formal or casual wear', 360, 41.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Cardigan', 'Soft and cozy cardigan for layering', 510, 37.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Kids'' Tights', 'Comfortable and stretchy tights for girls', 650, 16.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Tuxedo', 'Formal tuxedo for special occasions', 100, 250.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Evening Gown', 'Elegant evening gown for formal events', 130, 300.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Men''s Sports Jersey', 'Breathable sports jersey for active wear', 470, 32.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Clothing'), 'Women''s Leggings', 'Versatile and comfortable leggings for everyday wear', 600, 29.99);

-- Books
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'The Great Novel', 'A captivating fiction novel', 50, 15.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'History of the World', 'A comprehensive history book', 30, 29.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Science for Beginners', 'An introductory science book', 70, 12.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Cookbook: Delicious Recipes', 'A collection of tasty and easy recipes', 40, 18.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Mystery Thriller', 'A suspenseful mystery novel', 60, 16.20),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Biography of a Legend', 'The life story of an influential figure', 35, 22.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Self-Help Guide', 'Practical advice for personal growth', 55, 14.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Children''s Storybook', 'A delightful story for young readers', 80, 9.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Fantasy Adventure', 'An epic tale of magic and adventure', 45, 17.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Poetry Collection', 'A compilation of beautiful poems', 65, 11.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Travel Guide: Europe', 'A comprehensive guide to European travel', 25, 25.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Classic Literature', 'A timeless work of literary art', 52, 10.90),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Young Adult Novel', 'A compelling story for teenage readers', 75, 13.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Business Strategy Book', 'Insights into effective business management', 38, 28.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Science Fiction Classic', 'A groundbreaking work of science fiction', 48, 19.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Art History Book', 'A journey through the history of art', 28, 31.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Philosophy Textbook', 'An introduction to philosophical concepts', 42, 24.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Graphic Novel', 'A visually engaging story told through comics', 58, 16.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Language Learning Book (Spanish)', 'A guide to learning the Spanish language', 62, 14.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Psychology Today', 'A book exploring modern psychology', 33, 21.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Historical Fiction', 'A novel set in a historical period', 57, 18.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Contemporary Romance', 'A modern love story', 68, 12.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Humor Collection', 'A selection of funny stories and essays', 72, 10.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Educational Workbook', 'A book designed for learning and practice', 90, 8.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Digital Marketing Guide', 'A book on marketing strategies for the digital age', 39, 27.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Coding for Dummies', 'An easy-to-understand guide to programming', 88, 17.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Parenting Handbook', 'A guide to raising children', 53, 19.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Vegetarian Cookbook', 'A collection of recipes for vegetarian dishes', 47, 20.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'DIY Home Repair', 'A guide to do-it-yourself home repairs', 61, 23.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Books'), 'Mindfulness Meditation', 'A book on practicing mindfulness and meditation', 66, 15.50);

-- Home Goods
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Sofa (Three-Seater)', 'Comfortable three-seater sofa for the living room', 20, 499.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Coffee Table (Wooden)', 'Solid wood coffee table with a classic design', 35, 129.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Dining Chair (Set of 4)', 'Modern dining chairs with comfortable seating', 40, 199.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Bedding Set (Queen)', 'Complete queen-size bedding set', 50, 89.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Throw Pillow (Decorative)', 'Stylish decorative throw pillow for sofas and beds', 80, 25.20),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Curtains (Blackout)', 'Blackout curtains to block out light', 60, 49.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Area Rug (Living Room)', 'Soft and stylish area rug for the living room', 25, 149.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Table Lamp (Modern)', 'Modern table lamp for bedside or desk', 70, 34.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Wall Art (Abstract)', 'Abstract art piece to decorate your walls', 45, 59.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Dinnerware Set (4 Place Settings)', 'Complete dinnerware set for four people', 30, 79.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Glassware Set (Wine Glasses - 6)', 'Set of six elegant wine glasses', 55, 42.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Storage Ottoman', 'Versatile storage ottoman for extra seating and storage', 65, 75.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Floor Lamp (Standing)', 'Standing floor lamp for ambient lighting', 75, 89.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Decorative Vase', 'Elegant vase for displaying flowers or as a standalone piece', 90, 29.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Wall Mirror', 'Stylish wall mirror to enhance your space', 50, 69.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Bedside Table', 'Convenient bedside table with drawer', 40, 110.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Bookshelf (5-Shelf)', 'Five-shelf bookshelf for organizing your books and decor', 30, 149.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Kitchen Island', 'Functional kitchen island with storage', 20, 299.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Patio Set (4-Piece)', 'Four-piece patio set for outdoor seating', 25, 349.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Hammock', 'Relaxing hammock for outdoor leisure', 40, 79.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Shower Curtain', 'Stylish and waterproof shower curtain', 100, 24.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Bath Towel Set', 'Set of soft and absorbent bath towels', 95, 39.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Comforter Set (King)', 'Luxurious comforter set for a king-size bed', 45, 120.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Pillowcase Set (Silk)', 'Set of silk pillowcases for a comfortable sleep', 110, 45.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Throw Blanket', 'Cozy throw blanket for snuggling up', 120, 32.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Scented Candles (Set of 3)', 'Set of three scented candles for relaxation', 130, 27.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Picture Frame Set', 'Set of multiple picture frames for displaying memories', 85, 55.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Wall Clock', 'Decorative wall clock for any room', 70, 40.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Doormat', 'Durable doormat to welcome guests', 140, 19.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Home Goods'), 'Vase Set', 'Set of vases of varying sizes', 105, 65.00);

-- Sports & Outdoors
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Mountain Bike', 'Durable mountain bike for off-road trails', 30, 599.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Running Shoes', 'Lightweight running shoes for optimal performance', 80, 99.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Camping Tent (4-Person)', 'Spacious tent for camping trips', 40, 249.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Yoga Mat', 'Non-slip yoga mat for comfortable workouts', 100, 25.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Basketball', 'Official size basketball for indoor and outdoor play', 90, 29.20),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Hiking Backpack', 'Durable backpack for hiking and trekking', 50, 79.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Swimming Goggles', 'Comfortable and leak-proof swimming goggles', 120, 15.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Tennis Racket', 'High-quality tennis racket for players of all levels', 60, 119.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Football', 'Official size football for matches and practice', 110, 34.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Skateboard', 'Durable skateboard for street and park riding', 70, 75.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Golf Clubs (Set)', 'Complete set of golf clubs for beginners', 20, 399.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Kayak', 'Single-person kayak for recreational paddling', 35, 299.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Surfboard', 'Durable surfboard for riding the waves', 25, 449.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Climbing Shoes', 'Specialized shoes for rock climbing', 45, 129.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Archery Set', 'Complete archery set for target practice', 55, 199.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Fishing Rod and Reel Combo', 'Combo set for fishing enthusiasts', 65, 89.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Badminton Set', 'Set includes rackets and shuttlecocks for badminton', 130, 49.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Volleyball', 'Official size volleyball for beach or court play', 105, 27.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Boxing Gloves', 'Padded gloves for boxing and training', 85, 69.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Roller Skates', 'Adjustable roller skates for recreational skating', 95, 65.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Diving Mask and Snorkel Set', 'Set for snorkeling and diving adventures', 75, 55.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Frisbee', 'Classic frisbee for outdoor fun', 150, 12.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Croquet Set', 'Complete croquet set for lawn games', 40, 149.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Horseshoes Set', 'Complete horseshoes set for outdoor play', 50, 99.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Pickleball Paddles (Set of 2)', 'Set of two paddles for pickleball', 115, 79.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Slackline Kit', 'Kit for setting up a slackline for balance training', 60, 89.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Trampoline', 'Outdoor trampoline for fun and exercise', 20, 349.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Water Skis', 'Pair of water skis for water sports', 30, 299.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Snowshoes', 'Pair of snowshoes for winter hiking', 40, 179.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Sports & Outdoors'), 'Ice Skates', 'Pair of ice skates for rink or pond skating', 80, 89.00);

-- Beauty & Personal Care
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Facial Cleanser', 'Gentle cleanser for all skin types', 200, 15.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Moisturizer', 'Hydrating moisturizer for daily use', 180, 22.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Shampoo', 'Nourishing shampoo for healthy hair', 250, 12.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Conditioner', 'Smoothing conditioner for soft hair', 230, 14.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Lipstick', 'Long-lasting lipstick in various shades', 300, 10.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Mascara', 'Volumizing mascara for dramatic lashes', 270, 13.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Eyeliner', 'Precision eyeliner for defined eyes', 240, 9.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Foundation', 'Full coverage foundation for flawless skin', 190, 28.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Blush', 'Natural-looking blush for a radiant complexion', 210, 16.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Perfume', 'Elegant perfume with a floral scent', 150, 45.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Cologne', 'Masculine cologne with a woody aroma', 140, 40.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Hair Spray', 'Strong hold hair spray for styling', 260, 11.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Hair Gel', 'Styling gel for various hairstyles', 220, 8.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Nail Polish', 'High-shine nail polish in trendy colors', 350, 7.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Nail Polish Remover', 'Gentle and effective nail polish remover', 320, 5.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Body Lotion', 'Hydrating body lotion for smooth skin', 290, 17.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Body Wash', 'Refreshing body wash for a luxurious shower experience', 310, 10.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Sunscreen', 'Broad spectrum sunscreen for sun protection', 170, 19.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Face Mask', 'Rejuvenating face mask for a spa-like treatment', 205, 6.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Eye Cream', 'Nourishing eye cream to reduce wrinkles', 160, 32.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Shaving Cream', 'Rich shaving cream for a smooth shave', 280, 9.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Aftershave Balm', 'Soothing aftershave balm to calm skin', 255, 18.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Hair Brush', 'High-quality hair brush for detangling and styling', 275, 14.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Toothbrush', 'Electric toothbrush for optimal dental hygiene', 195, 40.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Toothpaste', 'Whitening toothpaste for a bright smile', 330, 6.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Floss', 'Dental floss for cleaning between teeth', 340, 4.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Mouthwash', 'Antiseptic mouthwash for fresh breath', 305, 8.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Deodorant', 'Long-lasting deodorant for all-day freshness', 315, 7.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Hand Sanitizer', 'Effective hand sanitizer for germ protection', 400, 3.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Beauty & Personal Care'), 'Cotton Swabs', 'Soft cotton swabs for various uses', 380, 2.50);

-- Toys & Games
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Building Blocks Set', 'Set of colorful building blocks for creative play', 150, 29.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Action Figure', 'Detailed action figure from a popular movie', 200, 19.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Board Game', 'Fun board game for family and friends', 100, 25.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Puzzle (1000 Pieces)', 'Challenging 1000-piece jigsaw puzzle', 120, 18.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Remote Control Car', 'Fast remote control car with realistic features', 180, 49.20),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Doll', 'Fashion doll with stylish outfits', 250, 24.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Stuffed Animal', 'Soft and cuddly stuffed animal', 160, 15.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Educational Toy', 'Interactive toy for learning and development', 80, 34.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Outdoor Playset', 'Durable playset for backyard fun', 90, 399.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Card Game', 'Classic card game for all ages', 300, 9.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Video Game', 'Popular video game for consoles', 220, 59.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Train Set', 'Electric toy train set with tracks', 140, 89.90),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Science Kit', 'Hands-on science kit for experiments', 110, 29.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Art Set', 'Complete art set with various supplies', 280, 35.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Musical Toy', 'Musical instrument toy for kids', 130, 22.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Sports Toy', 'Toy for playing sports like basketball or soccer', 70, 19.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Ride-On Toy', 'Ride-on toy vehicle for toddlers', 105, 69.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Inflatable Pool', 'Inflatable pool for summer fun', 95, 45.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Water Gun', 'High-capacity water gun for water fights', 210, 12.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Kite', 'Easy-to-fly kite for outdoor adventures', 170, 14.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Robot Toy', 'Interactive robot toy with lights and sounds', 190, 79.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Dollhouse', 'Detailed dollhouse with furniture', 125, 99.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Kitchen Set', 'Play kitchen set with accessories', 135, 65.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Tool Set', 'Set of toy tools for pretend play', 155, 39.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Doctor Kit', 'Kit with toy medical instruments', 145, 27.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Cash Register', 'Toy cash register with play money', 165, 44.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Microphone', 'Toy microphone for singing and performances', 185, 21.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Telescope', 'Toy telescope for stargazing', 115, 55.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Bowling Set', 'Indoor bowling set for kids', 175, 32.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Toys & Games'), 'Toy Dart Board', 'Safe toy dart board with soft darts', 195, 29.00);

-- Automotive
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Car Battery', 'High-performance car battery', 50, 120.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Brake Pads (Set)', 'Set of front brake pads', 80, 65.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Oil Filter', 'Premium oil filter', 100, 12.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Air Filter', 'Standard air filter', 90, 15.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Spark Plugs (Set of 4)', 'Set of four spark plugs', 70, 30.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Headlight Bulb', 'High-intensity headlight bulb', 120, 25.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Taillight Assembly', 'Complete taillight assembly', 60, 85.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Windshield Wipers (Pair)', 'Pair of durable windshield wipers', 110, 22.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Car Floor Mats (Set)', 'Set of four car floor mats', 130, 40.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Car Cover', 'Waterproof car cover', 40, 75.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Tire Pressure Gauge', 'Digital tire pressure gauge', 150, 18.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Car Charger', 'USB car charger for mobile devices', 140, 15.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Dashboard Camera', 'High-definition dashboard camera', 50, 99.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'GPS Navigation System', 'Portable GPS navigation system', 30, 149.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Car Vacuum Cleaner', 'Portable car vacuum cleaner', 80, 45.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Jumper Cables', 'Heavy-duty jumper cables', 90, 28.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'First Aid Kit', 'Automotive first aid kit', 100, 35.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Emergency Roadside Kit', 'Complete emergency roadside kit', 20, 120.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Car Wax', 'High-quality car wax', 110, 20.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Car Wash Soap', 'Concentrated car wash soap', 120, 10.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Wheel Cleaner', 'Effective wheel cleaner', 105, 14.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Tire Shine', 'Long-lasting tire shine spray', 115, 12.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Interior Cleaner', 'All-purpose interior cleaner', 130, 9.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Leather Conditioner', 'Leather conditioner for car seats', 95, 18.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Car Air Freshener', 'Long-lasting car air freshener', 200, 4.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Engine Oil (5 Quart)', '5 quarts of synthetic engine oil', 65, 40.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Transmission Fluid', 'Automatic transmission fluid', 75, 16.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Coolant', 'Antifreeze coolant', 85, 18.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Brake Fluid', 'High-performance brake fluid', 95, 12.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Automotive'), 'Power Steering Fluid', 'Power steering fluid', 100, 10.00);

-- Food & Beverage
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Ground Coffee', 'Premium ground coffee blend', 100, 8.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Green Tea Bags', 'Organic green tea bags', 120, 6.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Olive Oil', 'Extra virgin olive oil', 80, 15.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Balsamic Vinegar', 'Aged balsamic vinegar', 60, 12.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Pasta (Spaghetti)', 'Imported Italian spaghetti', 200, 3.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Tomato Sauce', 'Organic tomato sauce', 180, 4.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Canned Tuna', 'Canned tuna in olive oil', 250, 2.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Salmon Fillet', 'Fresh salmon fillet', 50, 18.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Chicken Breast', 'Boneless, skinless chicken breast', 150, 7.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Ground Beef', 'Lean ground beef', 120, 9.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Cheddar Cheese', 'Sharp cheddar cheese', 90, 6.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Milk (Gallon)', 'Whole milk gallon', 200, 4.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Eggs (Dozen)', 'Large brown eggs', 300, 3.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Bread (Loaf)', 'Whole wheat bread loaf', 250, 3.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Apples (Bag)', 'Bag of fresh apples', 180, 5.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Bananas (Bunch)', 'Bunch of ripe bananas', 220, 2.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Orange Juice', 'Freshly squeezed orange juice', 100, 7.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Soda (6-Pack)', '6-pack of assorted soda', 150, 5.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Bottled Water (24-Pack)', '24-pack of bottled water', 300, 6.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Potato Chips', 'Large bag of potato chips', 280, 4.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Chocolate Bar', 'Premium dark chocolate bar', 200, 3.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Candy (Bag)', 'Assorted candy bag', 230, 5.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Ice Cream (Half Gallon)', 'Half gallon of vanilla ice cream', 120, 6.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Frozen Pizza', 'Large frozen pizza', 170, 8.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Cereal', 'Family size cereal box', 190, 7.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Oatmeal', 'Large container of oatmeal', 210, 5.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Peanut Butter', 'Creamy peanut butter jar', 160, 6.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Jelly', 'Assorted fruit jelly jar', 140, 4.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Mayonnaise', 'Large jar of mayonnaise', 130, 5.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Food & Beverage'), 'Ketchup', 'Large bottle of ketchup', 150, 4.50);

-- Jewelry
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Diamond Ring', 'Elegant diamond solitaire ring', 10, 2500.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Gold Necklace', '18K gold chain necklace', 20, 850.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Silver Earrings', 'Sterling silver hoop earrings', 50, 75.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Pearl Bracelet', 'Classic pearl bracelet', 30, 300.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Sapphire Pendant', 'Blue sapphire pendant on a silver chain', 25, 450.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Ruby Ring', 'Stunning ruby and diamond ring', 15, 1800.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Emerald Earrings', 'Elegant emerald drop earrings', 18, 600.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Amethyst Necklace', 'Amethyst gemstone necklace', 40, 120.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Topaz Bracelet', 'Blue topaz tennis bracelet', 22, 280.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Opal Ring', 'Unique opal and gold ring', 12, 900.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Diamond Studs', 'Classic diamond stud earrings', 45, 550.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Gold Hoop Earrings', 'Large gold hoop earrings', 60, 220.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Silver Chain', 'Sterling silver chain necklace', 70, 90.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Pearl Necklace', 'Single strand pearl necklace', 35, 400.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Sapphire Earrings', 'Blue sapphire stud earrings', 28, 380.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Ruby Pendant', 'Ruby heart pendant', 17, 700.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Emerald Ring', 'Emerald and diamond halo ring', 10, 1200.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Amethyst Earrings', 'Amethyst dangle earrings', 38, 150.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Topaz Necklace', 'Blue topaz pendant necklace', 20, 250.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Opal Earrings', 'Opal drop earrings', 14, 650.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Rose Gold Ring', 'Rose gold band with diamonds', 24, 1100.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'White Gold Necklace', 'White gold chain with a pendant', 32, 950.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Platinum Bracelet', 'Platinum tennis bracelet', 8, 3000.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Titanium Ring', 'Modern titanium ring for men', 55, 180.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Wooden Earrings', 'Handcrafted wooden earrings', 80, 45.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Beaded Necklace', 'Colorful beaded necklace', 90, 60.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Leather Bracelet', 'Braided leather bracelet', 75, 50.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Anklet', 'Delicate silver anklet', 100, 30.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Toe Ring', 'Sterling silver toe ring', 120, 25.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Jewelry'), 'Brooch', 'Vintage-style brooch', 40, 100.00);

-- Watches
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Luxury Gold Watch', 'Elegant gold watch with diamond accents', 5, 5000.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Stainless Steel Watch', 'Classic stainless steel watch', 15, 800.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Leather Strap Watch', 'Stylish watch with a genuine leather strap', 25, 350.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Sports Watch', 'Durable sports watch with multiple functions', 30, 200.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Smartwatch', 'Smartwatch with fitness tracking and notifications', 20, 400.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Chronograph Watch', 'Chronograph watch with stopwatch function', 18, 600.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Diving Watch', 'Water-resistant diving watch', 12, 750.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Pilot Watch', 'Classic pilot watch design', 10, 900.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Dress Watch', 'Elegant dress watch for formal occasions', 22, 550.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Digital Watch', 'Digital watch with multiple time zones', 40, 150.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Automatic Watch', 'Automatic self-winding watch', 14, 1200.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Quartz Watch', 'Precise quartz movement watch', 35, 250.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Minimalist Watch', 'Simple and elegant minimalist watch', 50, 180.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Vintage Watch', 'Vintage-style watch with retro design', 8, 1000.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Rose Gold Watch', 'Rose gold plated watch', 20, 950.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Ceramic Watch', 'Durable ceramic watch', 18, 1100.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Titanium Watch', 'Lightweight titanium watch', 28, 850.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Wooden Watch', 'Unique wooden watch', 60, 220.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Pocket Watch', 'Classic pocket watch', 10, 450.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Nurse Watch', 'Practical nurse watch with clip', 70, 80.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Fashion Watch', 'Trendy fashion watch', 90, 120.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Kids Watch', 'Durable and fun watch for children', 100, 50.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'GPS Watch', 'GPS tracking watch', 30, 300.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Solar Watch', 'Solar-powered watch', 45, 320.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'World Time Watch', 'Watch with world time function', 20, 600.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Moon Phase Watch', 'Watch with moon phase display', 16, 1300.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Skeleton Watch', 'Watch with visible mechanical movement', 12, 1500.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Open Heart Watch', 'Watch with a partial view of the movement', 18, 1100.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Perpetual Calendar Watch', 'Watch with perpetual calendar', 6, 4000.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Watches'), 'Tourbillon Watch', 'High-end watch with tourbillon complication', 2, 10000.00);

-- Bags & Luggage
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Laptop Backpack', 'Durable backpack with laptop compartment', 50, 79.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Travel Suitcase', 'Hard-shell suitcase for travel', 30, 149.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Duffel Bag', 'Spacious duffel bag for gym or travel', 40, 59.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Messenger Bag', 'Stylish messenger bag for everyday use', 60, 69.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Tote Bag', 'Versatile tote bag for shopping or work', 80, 39.20),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Handbag', 'Elegant handbag for formal occasions', 50, 99.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Wallet', 'Leather wallet with multiple compartments', 100, 49.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Crossbody Bag', 'Compact crossbody bag for hands-free convenience', 70, 45.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Rolling Luggage', 'Rolling suitcase with spinner wheels', 25, 179.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Garment Bag', 'Garment bag for protecting formal wear', 35, 129.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Beach Bag', 'Large beach bag for carrying essentials', 90, 29.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Diaper Bag', 'Functional diaper bag with changing pad', 45, 89.90),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Camera Bag', 'Padded camera bag for protecting equipment', 55, 75.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Wine Carrier Bag', 'Insulated wine carrier bag', 65, 49.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Tool Bag', 'Durable tool bag with compartments', 40, 65.25),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Lunch Bag', 'Insulated lunch bag for carrying meals', 120, 25.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Cosmetic Bag', 'Compact cosmetic bag for travel', 110, 19.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Drawstring Bag', 'Lightweight drawstring bag', 150, 15.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Saddlebag', 'Motorcycle saddlebag', 20, 199.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Hydration Pack', 'Hydration pack for hiking and biking', 30, 85.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Pet Carrier', 'Comfortable pet carrier', 75, 55.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Bowling Bag', 'Durable bowling ball bag', 25, 60.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Archery Bow Case', 'Protective case for archery bow', 15, 120.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Golf Travel Bag', 'Travel bag for golf clubs', 20, 200.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Skateboard Bag', 'Bag for carrying a skateboard', 80, 30.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Yoga Mat Bag', 'Bag for carrying a yoga mat', 100, 20.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Pencil Case', 'Pencil case for stationery', 200, 10.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Reusable Shopping Bag', 'Eco-friendly reusable shopping bag', 300, 5.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Dry Bag', 'Waterproof dry bag for outdoor activities', 90, 40.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Bags & Luggage'), 'Paper Bag', 'Recyclable paper bag', 500, 1.00);

-- Shoes
INSERT INTO product (id, category_id, name, description, available_quantity, price) VALUES
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Running Shoes', 'Lightweight running shoes for performance', 100, 99.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Casual Sneakers', 'Comfortable sneakers for everyday wear', 150, 79.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Formal Dress Shoes', 'Elegant dress shoes for formal occasions', 80, 129.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Hiking Boots', 'Durable hiking boots for outdoor adventures', 60, 149.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Sandals', 'Comfortable sandals for warm weather', 200, 39.20),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'High Heels', 'Stylish high heels for women', 120, 89.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Flats', 'Versatile flats for casual or dressy outfits', 180, 59.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Boots', 'Durable boots for all seasons', 100, 119.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Slippers', 'Cozy slippers for indoor comfort', 250, 29.99),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Athletic Shoes', 'Performance athletic shoes for sports', 90, 109.00),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Loafers', 'Classic loafers for a stylish look', 110, 85.75),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Mules', 'Trendy mules for a fashionable touch', 130, 69.90),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Clogs', 'Comfortable clogs for casual wear', 140, 49.50),
(nextval('product_seq'), (SELECT id FROM category WHERE name = 'Shoes'), 'Espadrilles', 'Lightweight espadrilles for summer', 160, 55.30);
