spring:
  application:
    name: payment-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8888
